# Generated by Django 6.0.2 on 2026-03-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mypatients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('medical_history', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
